name: example

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_ui_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
