name: flutter_ui_kit
description: "A customizable UI component library for Flutter."
publish_to: 'none'
version: 0.1.0
homepage: https://github.com/beewoo01/arte_ui_kit.git
repository: https://github.com/beewoo01/arte_ui_kit.git

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
